name: optoolize

on:
  workflow_dispatch:
    inputs:
      ipa_gdrive:
        description: "Google Drive direct link for IPA"
        required: true
        default: "https://drive.google.com/uc?export=download&id=1Y0xHaxuKUUCoph7p_ZEG-jbXHZFHH49M"
      dylib_gdrive:
        description: "Google Drive direct link for Frida dylib"
        required: true
        default: "https://drive.google.com/uc?export=download&id=1p8dw1tamEhESE8u6wOYn0VpCObgsJYZj"

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure Python and gdown
        run: |
          python3 -m pip install --upgrade pip
          pip install gdown

      - name: Prepare workdir
        run: mkdir workdir

      - name: Download IPA and dylib via gdown
        run: |
          cd workdir
          gdown "${{ github.event.inputs.ipa_gdrive }}" -O crssplay_frida_localpatched.ipa
          gdown "${{ github.event.inputs.dylib_gdrive }}" -O frida-gadget-17.3.2-ios-universal.dylib
          echo "Downloaded files:"
          ls -lh
          echo "IPA first 256 bytes:"
          hexdump -C -n 256 crssplay_frida_localpatched.ipa || true
          echo "DYLIB first 256 bytes:"
          hexdump -C -n 256 frida-gadget-17.3.2-ios-universal.dylib || true

      - name: Get optool
        run: |
          brew install optool || brew install --HEAD optool || true

      - name: Unzip IPA
        run: |
          mkdir work_unzip
          unzip workdir/crssplay_frida_localpatched.ipa -d work_unzip

      - name: Copy dylib into Frameworks
        run: |
          APP_PATH=$(find work_unzip/Payload -name "*.app" | head -n 1)
          mkdir -p "$APP_PATH/Frameworks"
          cp workdir/frida-gadget-17.3.2-ios-universal.dylib "$APP_PATH/Frameworks/"
          echo "Copied dylib into $APP_PATH/Frameworks"

      - name: Inject LC_LOAD_DYLIB into dfxm
        run: |
          APP_PATH=$(find work_unzip/Payload -name "*.app" | head -n 1)
          EXEC="$APP_PATH/dfxm"
          optool install -c load -p "@executable_path/Frameworks/frida-gadget-17.3.2-ios-universal.dylib" -t "$EXEC" || true

      - name: Repack IPA
        run: |
          cd work_unzip
          zip -r ../crssplay_frida_patched.ipa Payload

      - name: Upload patched IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: crssplay_frida_patched
          path: workdir/../crssplay_frida_patched.ipa
